version: '3.8'
services:
  mongodb:
    image: mongo:7
    container_name: foodflow-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: foodflow_menu
    volumes:
      - mongodb_data:/data/db

  ms-menu:
    build: .
    container_name: ms-menu
    restart: always
    ports:
      - "8003:8003"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/foodflow_menu?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data: